"""Render the bilingual personal blog; only the academic homepage is indexed."""
import hashlib, json, html

def render_blog(root, tr, theme_init, theme_button):
    note = json.loads((root/'blog/posts.json').read_text())
    def asset(path):
        return '/' + path + '?v=' + hashlib.sha256((root/path).read_bytes()).hexdigest()[:12]
    portrait=asset('assets/blog-character-seated-v1.webp')
    star='<svg class="name-spark" viewBox="0 0 24 34" aria-hidden="true"><path d="M12 1l2.8 9.2L23 13l-8.2 2.8L12 25l-2.8-9.2L1 13l8.2-2.8Z"/><path d="M6 27v6M3 30h6"/></svg>'
    gear='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m9 3-.6 2.4-2 .9L4 5.6 2 9l1.8 1.7v2.6L2 15l2 3.4 2.4-.7 2 .9L9 21h4l.6-2.4 2-.9 2.4.7 2-3.4-1.8-1.7v-2.6L20 9l-2-3.4-2.4.7-2-.9L13 3Z"/><circle cx="11" cy="12" r="3"/></svg>'
    links=f'<a href="/blog/" aria-current="page">Blog</a><a href="/#publications">{tr("Research","研究")}</a><a href="/">{tr("About","关于我")}</a>'
    header=f'''<header class="site-header"><div class="blog-header"><a class="identity" href="/" aria-label="Yongxue Xu — Homepage"><span>Yongxue</span>{star}<span>Xu</span></a><nav class="blog-nav" aria-label="Blog navigation">{links}</nav><div class="header-actions">{theme_button}<button id="language" type="button" aria-label="切换到中文">中文</button><button class="menu-toggle" type="button" aria-label="Menu" aria-expanded="false" aria-controls="mobile-menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button></div></div><nav id="mobile-menu" hidden aria-label="Mobile navigation">{links}</nav></header>'''
    scene=f'''<section class="scene" aria-label="Interactive rainbow"><h1 class="visually-hidden">Blog</h1><div class="rainbow-art"><canvas id="rainbow-scene" aria-hidden="true"></canvas></div><svg class="clouds" viewBox="0 0 1440 350" preserveAspectRatio="none" aria-hidden="true"><path class="cloud-far" d="M0 93C80 83 138 19 223 44S285 120 322 95C420 8 566 29 620 142C628 160 640 140 662 131C758 86 821 109 897 149C967 198 1002 138 1076 88C1218-8 1321-5 1440 12V350H0Z"/><path class="cloud-back" d="M0 16C80 14 155 60 208 143C279 254 364 132 503 192C559 218 594 229 628 216C743 169 822 177 902 225C920 240 921 221 944 197C1028 107 1117 123 1223 142C1299 156 1355 114 1440 108V350H0Z"/></svg><svg class="clouds clouds--front" viewBox="0 0 1440 350" preserveAspectRatio="none" aria-hidden="true"><path class="cloud-front" d="M0 193C139 102 370 138 492 177C629 220 727 269 785 338C796 352 805 350 828 339C1004 248 1160 276 1288 319C1311 328 1314 315 1322 296C1366 184 1401 132 1440 114V350H0Z"/></svg><div class="scene-portrait"><img src="{portrait}" alt="" width="397" height="720" fetchpriority="high" decoding="async"></div><div class="rainbow-tools"><button class="rainbow-settings" type="button" aria-label="Rainbow settings" aria-expanded="false" aria-controls="rainbow-controls">{gear}</button><div id="rainbow-controls" hidden><strong>{tr('Make it your rainbow','调一调你的彩虹')}</strong><label for="rainbow-motion">{tr('Movement','灵动程度')}</label><input id="rainbow-motion" type="range" min="0" max="100" value="65"><button id="rainbow-reset" type="button">{tr('Reset','恢复默认')}</button></div></div></section>'''
    def page(title, description, main, path, home=False):
        canonical='https://jerrysnow.me/'+path
        return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} — Yongxue Xu</title><meta name="description" content="{html.escape(description,quote=True)}"><meta name="robots" content="noindex, follow"><meta name="theme-color" content="#ffffff"><script>{theme_init}</script><link rel="canonical" href="{canonical}"><link rel="icon" href="data:,"><link rel="preload" href="{asset('blog/fonts/dm-sans-latin.woff2')}" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="{asset('blog/blog.css')}"><script src="{asset('blog/blog.js')}" defer></script></head><body class="{'blog-home' if home else 'blog-article'}"><a class="skip-link" href="#content">Skip to content</a>{header}{scene if home else ''}<main class="{'blog-layout' if home else 'article-main'}" id="content">{main}</main><footer><span>Yongxue Xu</span><a href="/">{tr('Back to homepage','返回主页')} <span aria-hidden="true">↗</span></a></footer></body></html>'''
    index=f'''<div class="writing"><h2 class="section-label">{tr('ARTICLES AND NOTES','文章与手记')}</h2><article class="post"><h3><a href="astradraw/">{tr(note['title_en'],note['title_zh'])}</a></h3><p class="post-summary">{tr(note['summary_en'],note['summary_zh'])}</p><p>{tr(note['paragraphs'][0]['en'],note['paragraphs'][0]['zh'])}</p><a class="read-link" href="astradraw/">{tr('Read more','阅读全文')}<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h13m-5-5 5 5-5 5"/></svg></a></article></div><aside class="blog-aside"><section><h2 class="section-label">{tr('EXPLORE BY TOPIC','按主题探索')}</h2><div class="topic-pills"><a href="/#publications">{tr('Research','研究')}</a><a href="astradraw/">{tr('Making','创作')}</a><a href="https://github.com/IamJerryXu?tab=repositories">{tr('Open source','开源')}</a><a href="https://inkmind-ai.com/" target="_blank" rel="noopener noreferrer">InkMind ↗</a></div></section><section class="elsewhere"><h2 class="section-label">{tr('A FEW THINGS I MADE','动手做的小作品')}</h2><a href="https://github.com/IamJerryXu/AstraDraw" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">→</span><span>AstraDraw <small>{tr('Editable research figures','可编辑的科研图')}</small></span></a><a href="https://inkmind-ai.com/" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">→</span><span>InkMind <small>{tr('A place for curious minds','好奇心相遇的地方')}</small></span></a></section></aside>'''
    article=f'''<a class="back" href="/blog/">← {tr('All writing','全部文章')}</a><p class="section-label">{tr('MAKING · ASTRADRAW','创作 · ASTRADRAW')}</p><h1 class="article-title">{tr(note['title_en'],note['title_zh'])}</h1><p class="article-deck">{tr(note['summary_en'],note['summary_zh'])}</p><div class="article-body">{''.join('<p>'+tr(p['en'],p['zh'])+'</p>' for p in note['paragraphs'])}</div><div class="source">{tr('Based on the public project documentation.','根据项目公开说明整理。')} <a href="{note['source_url']}" target="_blank" rel="noopener noreferrer">AstraDraw ↗</a></div>'''
    (root/'blog/index.html').write_text(page('Blog','Notes on research, making things, and following curiosity.',index,'blog/',True))
    (root/'blog/astradraw/index.html').write_text(page(note['title_en'],note['summary_en'],article,'blog/astradraw/'))
