"""Render the bilingual personal blog; only the academic homepage is indexed."""
import hashlib, json, html

def render_blog(root, tr, theme_init, theme_button):
    note = json.loads((root/'blog/posts.json').read_text())
    def asset(path):
        return '/' + path + '?v=' + hashlib.sha256((root/path).read_bytes()).hexdigest()[:12]
    portrait=asset('assets/previews/portrait-memoji-transparent-v1-480.webp')
    header=f'''<header class="site-header"><div class="blog-header"><a class="identity" href="/" aria-label="Yongxue Xu — Homepage">Yongxue<span class="name-dot" aria-hidden="true">·</span>Xu</a><nav class="blog-nav" aria-label="Blog navigation"><a href="/">{tr('Homepage','主页')}</a><a href="/blog/" aria-current="page">Blog</a><span class="nav-divider" aria-hidden="true"></span>{theme_button}<button id="language" type="button" aria-label="切换到中文">中文</button></nav></div></header>'''
    scene=f'''<section class="scene" aria-labelledby="blog-title"><div class="scene-inner"><div class="scene-copy"><p class="eyebrow">{tr('A PERSONAL NOTEBOOK','个人手记')}</p><h1 id="blog-title">Blog<span class="title-dot">.</span></h1><p class="scene-description">{tr('A little research. A little making.<br>Always a little curiosity.','一点研究，一点创作。<br>还有一直保留的好奇心。')}</p></div><div class="rainbow-art"><canvas id="rainbow-scene" aria-hidden="true"></canvas><div class="scene-portrait"><img src="{portrait}" alt="" width="480" height="640" decoding="async"></div></div><button class="rainbow-play" type="button" aria-label="Animate the rainbow"><span aria-hidden="true">✳</span>{tr('A little play','拨动彩虹')}</button></div><svg class="clouds clouds--back" viewBox="0 0 1440 240" preserveAspectRatio="none" aria-hidden="true"><path class="cloud-back" d="M0 70C120 5 170 138 265 95S421 2 545 96S700 136 790 76S942 7 1044 97S1190 161 1282 78S1380 22 1440 55V240H0Z"/></svg><svg class="clouds clouds--front" viewBox="0 0 1440 240" preserveAspectRatio="none" aria-hidden="true"><path class="cloud-front" d="M0 155C163 58 288 190 420 162S579 121 694 181S852 220 956 171S1131 96 1239 150S1385 165 1440 119V240H0Z"/></svg></section>'''
    def page(title, description, main, path, home=False):
        canonical='https://jerrysnow.me/'+path
        return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} — Yongxue Xu</title><meta name="description" content="{html.escape(description,quote=True)}"><meta name="robots" content="noindex, follow"><meta name="theme-color" content="#ffffff"><script>{theme_init}</script><link rel="canonical" href="{canonical}"><link rel="icon" href="data:,"><link rel="preload" href="{asset('blog/fonts/dm-sans-latin.woff2')}" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="{asset('blog/blog.css')}"><script src="{asset('blog/blog.js')}" defer></script></head><body class="{'blog-home' if home else 'blog-article'}"><a class="skip-link" href="#content">Skip to content</a>{header}{scene if home else ''}<main class="{'blog-layout' if home else 'article-main'}" id="content">{main}</main><footer><span>Yongxue Xu</span><a href="/">{tr('Back to homepage','返回主页')} <span aria-hidden="true">↗</span></a></footer></body></html>'''
    index=f'''<div class="writing"><h2 class="section-label">{tr('LATEST WRITING','最近的文字')}</h2><article class="post"><p class="post-label">{tr('Making · AstraDraw','创作 · AstraDraw')}</p><h3><a href="astradraw/">{tr(note['title_en'],note['title_zh'])}</a></h3><p class="post-summary">{tr(note['summary_en'],note['summary_zh'])}</p><p>{tr(note['paragraphs'][0]['en'],note['paragraphs'][0]['zh'])}</p><a class="read-link" href="astradraw/">{tr('Read the story','阅读全文')}<span aria-hidden="true">⟶</span></a></article></div><aside class="blog-aside"><section><h2 class="section-label">{tr('ABOUT THIS SPACE','关于这里')}</h2><p>{tr('A place for research notes, small projects, and ideas that are worth a closer look.','记录研究中的思考、动手做的小作品，以及值得多看一眼的想法。')}</p></section><section class="elsewhere"><h2 class="section-label">{tr('THINGS TO EXPLORE','也可以看看')}</h2><a href="https://github.com/IamJerryXu/AstraDraw" target="_blank" rel="noopener noreferrer"><span><strong>AstraDraw</strong><small>{tr('Making research visual','让研究被看见')}</small></span><span aria-hidden="true">↗</span></a><a href="https://inkmind-ai.com/" target="_blank" rel="noopener noreferrer"><span><strong>InkMind</strong><small>{tr('A community for curious minds','好奇心相遇的地方')}</small></span><span aria-hidden="true">↗</span></a></section></aside>'''
    article=f'''<a class="back" href="/blog/">← {tr('All writing','全部文章')}</a><p class="section-label">{tr('MAKING · ASTRADRAW','创作 · ASTRADRAW')}</p><h1 class="article-title">{tr(note['title_en'],note['title_zh'])}</h1><p class="article-deck">{tr(note['summary_en'],note['summary_zh'])}</p><div class="article-body">{''.join('<p>'+tr(p['en'],p['zh'])+'</p>' for p in note['paragraphs'])}</div><div class="source">{tr('Based on the public project documentation.','根据项目公开说明整理。')} <a href="{note['source_url']}" target="_blank" rel="noopener noreferrer">AstraDraw ↗</a></div>'''
    (root/'blog/index.html').write_text(page('Blog','Notes on research, making things, and following curiosity.',index,'blog/',True))
    (root/'blog/astradraw/index.html').write_text(page(note['title_en'],note['summary_en'],article,'blog/astradraw/'))
